// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKhngZnjQt68e3keFL0FN9xVAQticlb-8',
    appId: '1:219710007137:web:51b94240685dc33e154720',
    messagingSenderId: '219710007137',
    projectId: 'flower-studies',
    authDomain: 'flower-studies.firebaseapp.com',
    storageBucket: 'flower-studies.firebasestorage.app',
    measurementId: 'G-DFNH8R86GM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2TzfX0voNF4OavErvxXfqenxDHQbvzsk',
    appId: '1:219710007137:android:12b222dba22a8acc154720',
    messagingSenderId: '219710007137',
    projectId: 'flower-studies',
    storageBucket: 'flower-studies.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg_g6w97wmQ1PpetpzHUDYLNkO9dtx6mE',
    appId: '1:219710007137:ios:d322a53c8ee85497154720',
    messagingSenderId: '219710007137',
    projectId: 'flower-studies',
    storageBucket: 'flower-studies.firebasestorage.app',
    iosBundleId: 'com.example.appFlowerStudies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDg_g6w97wmQ1PpetpzHUDYLNkO9dtx6mE',
    appId: '1:219710007137:ios:d322a53c8ee85497154720',
    messagingSenderId: '219710007137',
    projectId: 'flower-studies',
    storageBucket: 'flower-studies.firebasestorage.app',
    iosBundleId: 'com.example.appFlowerStudies',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKhngZnjQt68e3keFL0FN9xVAQticlb-8',
    appId: '1:219710007137:web:5aa82c8a69179326154720',
    messagingSenderId: '219710007137',
    projectId: 'flower-studies',
    authDomain: 'flower-studies.firebaseapp.com',
    storageBucket: 'flower-studies.firebasestorage.app',
    measurementId: 'G-6KC8RSPHK9',
  );
}
